genome-nexus/genome-nexus-importer

notebooks/ensembl_identifiers.ipynb, scripts/make_one_canonical_transcript_per_gene.py
- uniprot hg19 assignments in notebook. Remove unassignable ones. PR opened to
vcf2maf
- there is overlap in approved, synonyms and previous symbols
- No changes to data
=> Follow up analysis uniprot hg19 and overlap hugo

scripts/make_one_canonical_transcript_per_gene.py
Fix https://github.com/genome-nexus/genome-nexus-importer/issues/18
=> Fix entrez_gene_id column name

data/Makefile, scripts/import_mongo.sh, scripts/transform_msk_insight_mutations.py
- Code is ready to review
- Added the actual input files under `data/insight/input/`
- Added the gzipped json file under `data/insight/export/`
=> Added import scripts for MSK Insight mutations

README.md
Added some information about which image/version we're using. 
Will be helpful for debugging version issues or updating.
=> Update Docs w/ MongoDB version

scripts/transform_signal_db_mutations.py
Fix knowledgesystems/signal#52
=> Make sure signal mutation chromosome values are always strings

data/Makefile, data/common_input/CCDS2Sequence.override.txt, scripts/add_enst_id_to_ptm.py
Fix genome-nexus/genome-nexus#491
=> Support CCDS2Sequence override file

scripts/transform_signal_db_mutations.py
Part of: https://github.com/knowledgesystems/signal/issues/112
=> Update signal to include germline biallelic data 

scripts/transform_vcf_to_tsv.py
Part of https://github.com/cBioPortal/cbioportal/issues/8470
remove "wrong clinvar data" from database, e.g. position is -1 (`-1` will be duplicated indexs, remove them in order to build the index for clinvar queries)
=> clean up clinvar data with -1 location

scripts/transform_vcf_to_tsv.py
Part of: https://github.com/cBioPortal/cbioportal/issues/8470
Clinvar delins sometimes not parsing correctly.
VCF -> MAF genomic location
- delins:1,111,T,CC    ->    1,111,111,T,CC
- delins:1,111,TT,C    ->    1,111,112,TT,C
- ins:1,111,T,TC    ->    1,111,112,-,C
- del:1,111,TC,T   ->    1,112,112,C,-
- substitution:1,111,T,C   ->    1,111,111,T,C
=> fix clinvar delins

data/Makefile, scripts/add_domains_hugo_ccds_refseq_exon_info_uniprot_to_ensembl_transcript.py, scripts/download_transcript_info_from_ensembl.py, scripts/make_one_canonical_transcript_per_gene.py, scripts/requirements.txt
Fix: https://github.com/genome-nexus/genome-nexus/issues/525
=> Update hgnc set file

.github/workflows/docker-image.yml
Add git action to publish image for both grch37 and grch38
=> Add git action to publish grch38 image

.github/workflows/docker-image.yml, Dockerfile
Build grch38 db image when we make a new publish
=> Build grch38 db when publish

.github/workflows/docker-image.yml
=> Fix build grcm image docker workflow

.github/workflows/docker-image.yml
=> fix docker tag for mutationassessor image

data/Makefile, data/common_input/version_info.txt, data/grch37_ensembl92/export/annotation_version.txt, data/grch38_ensembl92/export/annotation_version.txt, data/grch38_ensembl95/export/annotation_version.txt, scripts/annotation_version_file.py, scripts/import_mongo.sh
Part of: https://github.com/genome-nexus/genome-nexus/issues/648
=> Add more info to version API

README.md
These env variables need to be exported to have any effect
=> Fix env vars in README

.circleci/config.yml
=> Test circle ci push docker image

data/grch37_ensembl92/export/annotation_version.txt, data/grch38_ensembl92/export/annotation_version.txt, data/grch38_ensembl95/export/annotation_version.txt
Update version files and add clinvar
=> Update Version files

data/grch37_ensembl92/export/annotation_version.txt, data/grch38_ensembl92/input/annotation_version.txt, data/grch38_ensembl95/export/annotation_version.txt, scripts/import_mongo.sh
Reverts genome-nexus/genome-nexus-importer#92
The data is too big to be built by github action
=> Revert "Mutation assessor v4"

data/grch38_ensembl95/export/oncokb_cancer_genes_list_from_API.json
There were some issues with grch38_ensembl95 files, regenerate related files
=> Re-generate grch38_ensembl95 files

.circleci/config.yml, scripts/make_one_canonical_transcript_per_gene.py
Fix: https://github.com/genome-nexus/genome-nexus/issues/792
- Adding new isoform override: oncokb
- Separate mskcc and oncokb isoform
=> Separate mskcc and oncokb isoform override transcripts
